grid:
  # renovate: datasource=custom.nvidia-grid-driver depName=nvidia-grid-driver versioning=loose
  version: "512.161.08"
  url: "https://download.microsoft.com/download/8/d/a/fsdfsdfsd-3a9b-4e6a-bc9a-72ff64d7a13c/NVIDIA-Linux-x86_64-512.161.08-grid-azure.run"
